title: myhi.fi
description: Documents
theme: just-the-docs
logo: "/images/myhifi_lockup_red-wht_sm.png"
markdown: kramdown

url: https://just-the-docs.github.io

color_scheme: myhifi-dark

favicon_ico: "favicon.ico"


aux_links:
  View on GitHub: https://github.com/FidelisAnalog/Documentation/

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.4"
