title: myhi.fi
description: Documents
theme: just-the-docs

url: https://just-the-docs.github.io

color_scheme: myhifi-dark

aux_links:
  View on GitHub: https://github.com/FidelisAnalog/Documentation/
